# Lesson 1.7: Introduction to Pandas

**Duration:** 3 Hours  
**Format:** Interactive Zoom Session

## 📋 Pre-Class Setup
Please run the cell below to ensure your environment is ready. We will use `numpy` and `pandas` throughout this lesson.

In [ ]:
# "import" load a library so we can use it. Nickname after "as" save typing.
# pandas = tool for tables (like Excel). numpy = tool for number arrays/math.
import pandas as pd
import numpy as np

# print() show text/values in output below cell.
print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

---

## Part 1: Creating & Modifying Data Structures (60 min)

### Learning Objectives
By the end of this section, you will be able to:
- **Create** Series and DataFrames from raw data.
- **Modify** DataFrames by adding new columns and changing values.
- **Identify** the index and column components.
- **Detect** missing values using `isna()` and `notna()`.

### 📖 Concept: The Series
A Series is a one-dimensional array with labeled indices. It's the building block of a DataFrame.

In [ ]:
# [DEMO] Creating a Series
# [4, 7, -5, 3] a Python list — ordered group of values, in square brackets.
# index=[...] give each value a name/label instead of just number 0,1,2,3.
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
obj  # last line in cell auto-display, no print() needed in Jupyter

### 📖 Concept: The DataFrame
A DataFrame is a 2-dimensional labeled data structure. Think of it as a dictionary of Series objects (each column is a Series).

In [ ]:
# [DEMO] Creating a DataFrame from a dictionary
# {} curly braces = Python dictionary: "key": [values...] pairs.
# Each key become a column name, its list become that column's values.
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)  # turn dictionary into table
frame

In [ ]:
# .head(2) show first 2 rows only. Dot after frame call a "method" (action) on it.
frame.head(2)

### 💡 Concept Demo: Inspecting & Modifying
1. `head()` and `tail()`
2. Accessing columns (dictionary syntax vs dot syntax)
3. Adding a new column

In [ ]:
# [DEMO] Inspecting data
print("First 5 rows:")
display(frame.head())  # display() like print but render table nicely (Jupyter only)

# [DEMO] Accessing a column
# frame['pop'] grab one column by name, in quotes (string), inside square brackets.
print("Population column:")
display(frame['pop'])

In [ ]:
# [DEMO] Adding a new column with a scalar value
# frame['debt'] = 16.5 create new column named "debt", same value every row.
frame['debt'] = 16.5
frame

In [ ]:
# [DEMO] Adding a calculated column
# == compare each row's state to 'Ohio' — True if match, False if not.
# Result (True/False per row) become new column "eastern".
frame['eastern'] = frame.state == 'Ohio'
frame

### 📖 Concept: Detecting Missing Data
Real-world data often has missing values (shown as `NaN`). Use `isna()` and `notna()` to detect them.

In [ ]:
# [DEMO] Detecting missing values
# np.nan = "Not a Number", pandas/numpy's way of marking missing/empty data.
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])

print("Original data:")
display(data_with_nan)

print("\nWhich values are missing?")
display(data_with_nan.isna())  # isna() → True where value is NaN

print("\nWhich values are NOT missing?")
display(data_with_nan.notna())  # notna() → opposite of isna()

### 👋👋👋 Group Exercise 1: The Inventory System

**Scenario:** You manage a small grocery store. You need to track your fruit inventory.

**Tasks:**
1. Create a DataFrame named `inventory` from the provided dictionary `fruit_data`.
2. Add a new column `price` with values `[3.0, 4.0, 2.0, 5.0]`.
3. Add a column `total_value` which is `quantity * price`.
4. Create a boolean column `low_stock` that is `True` if quantity is less than 50.

In [ ]:
# [EXERCISE] Starter Code
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
# Hint: pd.DataFrame(fruit_data)
# inventory = ...

# Create DataFrame
inventory = pd.DataFrame(fruit_data)
# Display the DataFrame
print(inventory)

import pandas as pd

fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
inventory = pd.DataFrame(fruit_data)

# 2. Add Price
inventory['price'] = [3.0, 4.0, 2.0, 5.0]

# 3. Calculate Total Value (quantity * price)
inventory['total_value'] = inventory['quantity'] * inventory['price']

# 4. Flag Low Stock (quantity < 50)
inventory['low_stock'] = inventory['quantity'] < 50

print(inventory)

In [ ]:
inventory['low_stock'] == True # this is the boolean mask

In [ ]:
inventory[inventory['low_stock'] == True]  # show only rows where low_stock is True

---

## Part 2: Indexing and Selection (60 min)

### Learning Objectives
By the end of this section, you will be able to:
- **Differentiate** between label-based (`loc`) and position-based (`iloc`) indexing.
- **Apply** boolean filtering to select specific rows.
- **Drop** rows or columns from a DataFrame.
- **Modify** specific data points using selection.

In [ ]:
import numpy as np
arr = np.arange(16).reshape((4, 4))
print(arr)

In [18]:
# Setup for Demo
# np.arange(16) make list of numbers 0-15. .reshape((4,4)) fold it into 4 rows x 4 cols grid.
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# .loc["Colorado"] grab row by its label (name), not position number.
data.loc["Colorado"]

### 💡 Concept Demo: Loc vs Iloc
- **.loc[row_label, col_label]**: "Address" based.
- **.iloc[row_pos, col_pos]**: "GPS" based (integers).

In [ ]:
# [DEMO] Select 'Colorado' row using loc
print("--- Row by Label ---")
display(data.loc["Colorado"])

# [DEMO] Select 'Colorado' row using iloc (it's at index 1)
# iloc use plain position number (0,1,2,...) like list index, ignore row label.
print("\n--- Row by Position ---")
display(data.iloc[1])

In [ ]:
# [DEMO] Boolean Filtering
# Select rows where column 'three' is greater than 5
# data["three"] > 5 make True/False per row; data[...] keep only True rows.
data[data["three"] > 5]

### 📖 Concept: Dropping Rows and Columns
Use the `drop()` method to remove rows or columns. By default, it drops rows. Use `axis=1` or `axis="columns"` to drop columns.

In [11]:
# [DEMO] Dropping rows and columns
print("Drop rows 'Colorado' and 'Ohio':")
display(data.drop(["Colorado", "Ohio"]))  # drop() default remove rows by label

print("\nDrop column 'two':")
display(data.drop("two", axis=1))  # axis=1 tell pandas "two" a column, not row

Drop rows 'Colorado' and 'Ohio':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14   100

Drop column 'two':

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14   100

### 👋👋👋 Group Exercise 2: Data Detective

**Tasks:**
Using the `data` DataFrame provided above:
1. Select the rows for 'Utah' and 'New York' only.
2. Select the value in the 'two' column for 'Ohio' (should be 1).
3. Select all rows where column 'three' is greater than 5.
4. Update the value of 'four' in the 'New York' row to be 100.

In [23]:
# [EXERCISE] Write your code here
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data
# 1. Utah and New York
# Hint: data.loc[["Utah", "New York"]]
print("Rows for Utah and New York:")
data.loc[["Utah", "New York"]]
display(data.loc[["Utah", "New York"]])

Rows for Utah and New York:

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
# 2. 'two' for 'Ohio'
# Hint: data.loc["Ohio", "two"]
print("\nValue of 'two' for 'Ohio':")
data.loc["Ohio", "two"]
display(data.loc["Ohio", "two"])

1

In [22]:
# 3. Filter > 5
# Hint: data[data["three"] > 5]
print("\nRows where 'three' > 5:")
data[data["three"] > 5]
display(data[data["three"] > 5])

Rows where 'three' > 5:

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14   100

In [21]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data
# 4. Update value
# Hint: data.loc["New York", "four"] = 100
print("\nUpdating value of 'four' for 'New York' to 100:")
data.loc["New York", "four"] = 100
display(data)

Updating value of 'four' for 'New York' to 100:

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14   100

---

## Part 3: Function Application, Sorting, & Ranking (60 min)

### Learning Objectives
By the end of this section, you will be able to:
- **Sort** data by index or values.
- **Rank** data to handle ties.
- **Apply** custom functions to transform data.

In [24]:
# Setup Data
frame = pd.DataFrame({
    "b": [4, 7, -3, 2], 
    "a": [0, 1, 0, 1]
}, index=['Row1', 'Row2', 'Row3', 'Row4'])
frame

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

### 💡 Concept Demo: Sorting & Ranking
1. `sort_index()`
2. `sort_values(by=...)`
3. `rank()`

In [25]:
# [DEMO] Sort by values in column 'b'
frame.sort_values(by="b")

      b  a
Row3 -3  0
Row4  2  1
Row1  4  0
Row2  7  1

In [26]:
# [DEMO] Applying a function
# def = "define a function": a reusable block of code you name and call later.
# val is a placeholder name for whatever value get passed in when function run.
def label_size(val):
    return "Big" if val > 2 else "Small"  # one-line if/else: shorthand for if-else

# .apply(label_size) run label_size() on every value in column 'b', one by one.
frame['b_size'] = frame['b'].apply(label_size)
frame

      b  a b_size
Row1  4  0    Big
Row2  7  1    Big
Row3 -3  0  Small
Row4  2  1  Small

### 👋👋👋 Group Exercise 3: Leaderboard Logic

**Scenario:** You have exam scores. You need to rank them and assign a Pass/Fail status.

**Tasks:**
1. Run the starter code to generate the `scores` DataFrame.
2. Sort the DataFrame by 'Math' score in descending order (highest first).
3. Create a new column 'Math_Rank' using the `.rank()` method.
4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
5. Apply this function to the 'Math' column to create a new 'Status' column.

In [ ]:
# [EXERCISE] Starter Code
scores = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 55, 88, 72]
})

# Your code here
# 2. Hint: scores.sort_values(by="Math", ascending=False)
scores_sorted = scores.sort_values(by="Math", ascending=False)  # Sort by Math (highest → lowest)
print(scores_sorted)

   Student  Math  Science
2  Charlie    92       88
0    Alice    85       70
3    David    60       72
1      Bob    45       55

In [28]:
# 3. Hint: scores['Math_Rank'] = scores['Math'].rank()
scores['Math_Rank'] = scores['Math'].rank(ascending=False)      # Add a rank column for Math scores
print(scores)

   Student  Math  Science  Math_Rank
0    Alice    85       70        2.0
1      Bob    45       55        4.0
2  Charlie    92       88        1.0
3    David    60       72        3.0

In [29]:
# 4. Hint: def pass_fail(score): return "Pass" if score >= 60 else "Fail"
def pass_fail(score):                               # Define pass/fail function
    return "Pass" if score >= 60 else "Fail"

scores['Math_Result'] = scores['Math'].apply(pass_fail)     # Apply function to Math column
print(scores)

   Student  Math  Science  Math_Rank Math_Result
0    Alice    85       70        2.0        Pass
1      Bob    45       55        4.0        Fail
2  Charlie    92       88        1.0        Pass
3    David    60       72        3.0        Pass

In [30]:
# 5. Hint: scores['Status'] = scores['Math'].apply(pass_fail)
scores['Status'] = scores['Math'].apply(pass_fail)      # Add Status column based on Math scores
print(scores)

   Student  Math  Science  Math_Rank Math_Result Status
0    Alice    85       70        2.0        Pass   Pass
1      Bob    45       55        4.0        Fail   Fail
2  Charlie    92       88        1.0        Pass   Pass
3    David    60       72        3.0        Pass   Pass

## 🎓 Lesson Summary

1. **Data Structures:** Series (1D) and DataFrame (2D) are the building blocks.
2. **Missing Data:** Use `isna()` and `notna()` to detect missing values.
3. **Selection:** Use `.loc[]` for labels and `.iloc[]` for positions. Use `.drop()` to remove rows/columns.
4. **Operations:** Vectorized operations are faster than loops. Use `.apply()` for custom logic.
5. **Sorting:** Organize your data to find insights quickly.

**Next Steps:** In the next lesson, we will cover Data Cleaning (handling missing values) and Aggregation (GroupBy).